Add a default no-args constructor to ErrorFieldTypeContainer class so that it can be deserialized.
- Added a default no-args constructor to `ErrorFieldTypeContainer`.
- Added equals and hashCode methods to `Message` and `PaymentFailureNotificationContent`.
- Unit-tested that Jackson can deserialize `PaymentFailureNotification`.

I am a developer who integrates Adyen notification webhooks to our Spring application. We are having issues with the `PAYMENT_FAILURE` notification type.

Our Spring framework cannot deserialize the `PaymentFailureNotification` object received from Adyen. `PaymentFailureNotification.PaymentFailureNotificationContent.ErrorFieldTypeContainer` class doesn't have a default no-args constructor required by Jackson (utilized by Spring) to deserialize objects.

---
Stacktrace:

org.springframework.http.converter.HttpMessageConversionException: Type definition error: [simple type, class com.adyen.model.marketpay.ErrorFieldTypeContainer]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.adyen.model.marketpay.ErrorFieldTypeContainer` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
at [Source: (PushbackInputStream); line: 1, column: 173] (through reference chain: com.adyen.model.marketpay.notification.PaymentFailureNotification["content"]->com.adyen.model.marketpay.notification.PaymentFailureNotificationContent["errorFields"]->java.util.ArrayList[0])
at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:386) ~[spring-web-5.3.7.jar!/:5.3.7]
at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:342) ~[spring-web-5.3.7.jar!/:5.3.7]
at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodArgumentResolver.readWithMessageConverters(AbstractMessageConverterMethodArgumentResolver.java:185) ~[spring-webmvc-5.3.7.jar!/:5.3.7]
at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.readWithMessageConverters(RequestResponseBodyMethodProcessor.java:158) ~[spring-webmvc-5.3.7.jar!/:5.3.7]
at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.resolveArgument(RequestResponseBodyMethodProcessor.java:131) ~[spring-webmvc-5.3.7.jar!/:5.3.7]
at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:121) ~[spring-web-5.3.7.jar!/:5.3.7]
at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:170) ~[spring-web-5.3.7.jar!/:5.3.7]
at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137) ~[spring-web-5.3.7.jar!/:5.3.7]
at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[spring-webmvc-5.3.7.jar!/:5.3.7]
...
---
Our controller implementation:

@PostMapping("/paymentFailure")
public ResponseEntity<String> paymentFailure(@RequestBody PaymentFailureNotification notificationRequest) {
// Jackson fails to deserialize the PaymentFailureNotification
log.info("Received {}", notificationRequest.toString());
adyenNotificationConsumer.accept(notificationRequest);
return ResponseEntity.ok().body(ADYEN_ACCEPTED);
}
---
A unit test to reproduce the problem:

@Test
void tmp() throws Exception {
var json = """
{"eventType":"PAYMENT_FAILURE","content":{"errorMessage":null,"modificationMerchantReference":null,"modificationPspReference":null,"paymentMerchantReference":null,"paymentPspReference":null,"errorFieldList":[{"errorDescription":null,"errorCode":null,"fieldType":{"fieldName":"firstName","field":"abc","shareholderCode":null}}],"errorFields":[{"ErrorFieldType":{"errorDescription":null,"errorCode":null,"fieldType":{"fieldName":"firstName","field":"abc","shareholderCode":null}}}]},"error":null,"eventDate":0,"executingUserKey":null,"live":true,"pspReference":"TSTPSPR0001"}
""";
var mapper = new ObjectMapper();

PaymentFailureNotification paymentFailureNotification = mapper.reader()
.forType(PaymentFailureNotification.class).readValue(json); // fails with InvalidDefinitionException
}